### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by karolchmist** [ananthakumaran/u#3]
Hello Anantha,

First of all, thanks for creating this library. We are evaluating different solutions for serializing json in the URL and u is our preferred so far.

I have a small doubt about a case when a property may be optional. For example :

```javascript
const cart = {
  id : 123,
  giftCardId : undefined
}
```

giftCardId is not always present. Is there an axiomatic method of modeling this case? 

A workaround would be to model it as an array with maximum of one element. Other solution would be to add an 'optional' type which would permit null/undefined values. 

What do you think?

Cheers,
Karol

**Comment by ananthakumaran** [comment]
My memory is a bit hazy about this because it's been some time since I have written this library. I believe all the fields in an object are considered optional, we use one bit to encode that information https://github.com/ananthakumaran/u/blob/master/src/object.js#L13. So it should work without any issue.

**Comment by karolchmist** [comment]
Thanks for super fast reply! You are right, the properties of an object are optional. I'm closing the issue.
